---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(ggthemes)
library(broom)
library(ggbeeswarm)
library(tidytext)
library(ggpubr)
library(viridis)
```

```{r}
#read in the data (long, one row per season)
ratings <- read_csv("../data/IMDb_Economist_tv_ratings.csv")
ratings <- ratings %>% 
  mutate(periode = cut(x = date, 
                     breaks = c(ymd("1980-01-01"), ymd("1990-01-01"),
                                ymd("2000-01-01"), ymd("2010-01-01"),
                                ymd("2019-12-31")),
                     labels=c("1980s","1990s",
                              "2000s","2010s")))

```

```{r}
#wide version of the data (one row per show)
wide_ratings <- ratings %>% pivot_wider(id_cols = c(title, genres, periode),
                        names_from = seasonNumber,
                        names_prefix = "season_",
                        names_sort = TRUE,
                        values_from = av_rating,
                        values_fill = NA) %>% 
                unnest(cols = season_1:season_44)
```
### Frame A

```{r carlos}
#format data for hairball plot 
shows <- ratings %>%
  select(!share) %>%
  select(!seasonNumber) %>%
  mutate(date = (ymd(date))) %>%
  mutate(start_year = year(date)) %>%
  group_by(title) %>%
  filter(start_year == min(start_year))

# for bigraph
nodes_3 <- shows %>%
  select(title, genres) %>%
  group_by(title) %>% 
  unique() %>%
  tibble() %>%
  mutate(genres = gsub("-", "", genres)) %>%
  mutate(genres = gsub("Drama", "", genres)) %>%
  mutate(genres = gsub("Drama,", "",genres)) %>%
  unnest_tokens(output = describer_bigrams, input = genres, token = "ngrams", n = 2) %>% 
  count(describer_bigrams, sort = TRUE) %>%
  ungroup() %>%
  filter(!is.na(describer_bigrams))
```

***

Text about Carlos' plot


### Frame 2


```{r maelle}
rating_genre <- ratings %>% 
  group_by(title) %>% 
  nest() %>% 
  mutate(overall_rating= 
           map(data, 
               ~ (sum(.x$av_rating)/nrow(.x)))) %>% 
   ungroup() %>%
  unnest(cols = c(data, overall_rating)) %>% 
  separate(genres,into=c("genre1","genre2","genre3")
           ,sep = ",") %>% 
  pivot_longer(cols = c("genre1","genre2","genre3"),
               values_to = "genre") %>% 
  filter(!is.na(genre), seasonNumber==1) %>% 
  mutate(periode = cut(x = date, 
                     breaks = c( ymd("1980-01-01"),ymd("1990-01-01"),
                                ymd("2000-01-01"),ymd("2010-01-01"),
                                ymd("2019-12-31")),
                     labels=c("80's","90's",
                              "2000-2009","2010-2018")))  
  
 rating_genre <-rating_genre %>%  
  mutate(genre=fct_lump_n(genre, 7)) %>% 
  filter(genre!="Other")

  
nitys <- rating_genre %>% 
  filter(periode == "90's") %>% 
    plot_ly(x = ~overall_rating,
            y = ~genre,
            split = ~genre,
            orientation ="h",
    type = 'violin',
    box = list(visible = T),
    meanline = list(visible = T),  
    color = ~genre,
    showlegend=FALSE,
    text= ~paste('</br> Title: ', title, 
                 '</br> Rating:', overall_rating),
    points="all",
    hoverinfo='text'
    ) 
nitys <- nitys %>%
layout(
  title= "90's",
  yaxis=list(
    title="Genres"),
  xaxis=list(title="Rating"))

  
two <- rating_genre %>% 
  filter(periode == "2000-2009") %>% 
    plot_ly(x = ~overall_rating,
            y = ~genre,
            split = ~genre,
            orientation ="h",
    type = 'violin',
    box = list(visible = T),
    meanline = list(visible = T),  
    color = ~genre,
    showlegend=FALSE,
    text= ~paste('</br>Title: ', title, '</br> Rating:', overall_rating),
    points="all",
    hoverinfo='text') 
two <- two %>%
layout(
  title = "2000-2009",
  yaxis=list(
    title="Genres"),
  xaxis=list(title="Rating"))

  

 twoten <- rating_genre %>% 
  filter(periode == "2010-2018") %>% 
    plot_ly(x = ~overall_rating,
            y = ~genre,
            split = ~genre,
            orientation ="h",
            yaxis="",
    type = 'violin',
    box = list(visible = T),
    meanline = list(visible = T),  
    color = ~genre,
    showlegend=FALSE,
    text= ~paste('</br> Title: ', title, 
                 '</br> Rating:', overall_rating),
    points="all",
    hoverinfo='text')
twoten <- twoten %>%
layout(
  title = "2010-2019",
 yaxis=list(
    title="Genres"),
  xaxis=list(title="Rating"))


subplot(nitys,two,twoten, shareY = TRUE, titleY =TRUE)

  


  
  
  

```

***

Text about Maelle's plot


### Frame 3


```{r megan}
#Interactive table of top shows by year
top_shows <- ratings %>%
  select(title, date, av_rating, genres) %>%
  mutate(date = ymd(date),
         year = year(date)) %>%
  separate(genres,into=c("genre1","genre2","genre3")
           ,sep = ",") %>% 
  pivot_longer(cols = c("genre1","genre2","genre3"),
               values_to = "genre")
  

top_shows %>%
  filter(year == 2016) %>%
  group_by(genre) %>%
  slice_max(av_rating,n = 1) %>%
  ggplot +
  geom_col(aes(x = av_rating, y = title, fill = fct_reorder(genre, av_rating)))
  

```

***

The data table includes every show that had the highest 10 ratings by year between 1990 and 2018. One can search a year to see the top 10 shows of that year or search a show to see what year that show appeared in the top 10 as well. 

### Frame 4

```{r casey}
renew <- ratings %>%
  group_by(title) %>%
  mutate(overall_rat = mean(av_rating),
         renewed = max(seasonNumber > 1)) %>% 
  filter(seasonNumber == 1) %>% 
  summarize(title = title,
            renewed = as.logical(renewed),
            season1rat = av_rating,
            periode = periode)

nested_renew <- renew %>% group_by(periode) %>% nest()

renewed_stats <- nested_renew %>% 
  mutate(t_test = purrr::map(data, ~t.test(.x$season1rat ~ .x$renewed), data=.x)) %>% 
  mutate(summary = purrr::map(t_test, broom::glance)) %>% 
  unnest(cols=c(summary)) %>%
  ungroup() %>% 
  dplyr::select(periode, p.value) %>% 
  mutate(p.value = signif(p.value, digits=3),
         group1=FALSE,
         group2=TRUE) %>% 
  mutate(p.value = if_else(p.value < 5e-2, true=as.character(p.value), false="n.s."))

renew %>% 
  ggplot(aes(x=renewed, y=season1rat)) +
  stat_summary(fun = 'mean', geom="bar", fill="grey70") +
  geom_point(alpha=0.25) +
  facet_wrap(~periode) + 
  labs(x="Show Renewed",
       y = "Season 1 Rating") +
  theme(legend.position = "none") +
  stat_pvalue_manual(renewed_stats, label = "p.value", tip.length = 0.01, y.position=10.5) +
  theme_few() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# will try to have the info in this table
# (# shows Renewed or Not by decade)
# pop up when you scroll over each bar

#renew %>% group_by(periode, renewed) %>% summarise(n=n())
```


***

Text about Casey's plot